# use docker-compose up -d to start the network
# version 3 does not support setting memory limits for docker-compose
version: '2'
services:
  notary-node:
    image: corda/corda-zulu-java1.8-4.5:latest
    # hostnames need to be the same as in build.gradle, because they are baked into nodeInfo files
    hostname: notary-node
    mem_limit: 1g
    expose:
      - 10002 # p2p port
      - 10003 # Corda RPC port, map to a host port using ports directive if Corda shell access is required
    volumes:
      - ./pocCordApp/build/nodes/Notary/certificates:/opt/corda/certificates
      - ./pocCordApp/build/nodes/Notary/cordapps:/opt/corda/cordapps
      - ./pocCordApp/build/nodes/Notary/etc:/etc/corda
      - ./pocCordApp/build/nodes/Notary/network-parameters:/opt/corda/network-parameters
      - ./pocCordApp/build/nodes/Notary/logs:/opt/corda/logs
      - ./pocCordApp/build/nodes/Notary/drivers:/opt/corda/drivers
      - ./pocCordApp/build/nodes/Notary/persistence:/opt/corda/persistence
      - ./pocCordApp/build/nodes/Notary/additional-node-infos:/opt/corda/additional-node-infos
      # the following makes deployNode dir layout compatible with the expectations of the docker image
      - ./pocCordApp/build/nodes/Notary/persistence.mv.db:/opt/corda/persistence/persistence.mv.db
      - ./pocCordApp/build/nodes/Notary/persistence.trace.db:/opt/corda/persistence/persistence.trace.db
      - ./pocCordApp/build/nodes/Notary/node.conf:/etc/corda/node.conf
  partyb-node:
    image: corda/corda-zulu-java1.8-4.5:latest
    # hostnames need to be the same as in build.gradle, because they are baked into nodeInfo files
    hostname: partyb-node
    mem_limit: 1g
    expose:
      - 10008 # p2p port
      - 10009 # Corda RPC port, map to a host port using ports directive if Corda shell access is required
    volumes:
      - ./pocCordApp/build/nodes/PartyB/certificates:/opt/corda/certificates
      - ./pocCordApp/build/nodes/PartyB/cordapps:/opt/corda/cordapps
      - ./pocCordApp/build/nodes/PartyB/etc:/etc/corda
      - ./pocCordApp/build/nodes/PartyB/network-parameters:/opt/corda/network-parameters
      - ./pocCordApp/build/nodes/PartyB/logs:/opt/corda/logs
      - ./pocCordApp/build/nodes/PartyB/drivers:/opt/corda/drivers
      - ./pocCordApp/build/nodes/PartyB/persistence:/opt/corda/persistence
      - ./pocCordApp/build/nodes/PartyB/additional-node-infos:/opt/corda/additional-node-infos
      # the following makes deployNode dir layout compatible with the expectations of the docker image
      - ./pocCordApp/build/nodes/PartyB/persistence.mv.db:/opt/corda/persistence/persistence.mv.db
      - ./pocCordApp/build/nodes/PartyB/persistence.trace.db:/opt/corda/persistence/persistence.trace.db
      - ./pocCordApp/build/nodes/PartyB/node.conf:/etc/corda/node.conf
  partya-node:
    image: corda/corda-zulu-java1.8-4.5:latest
    # hostnames need to be the same as in build.gradle, because they are baked into nodeInfo files
    hostname: partya-node
    mem_limit: 1g
    expose:
      - 10005 # p2p port
      - 10006 # Corda RPC port, map to a host port using ports directive if Corda shell access is required
    volumes:
      - ./pocCordApp/build/nodes/PartyA/certificates:/opt/corda/certificates
      - ./pocCordApp/build/nodes/PartyA/cordapps:/opt/corda/cordapps
      - ./pocCordApp/build/nodes/PartyA/etc:/etc/corda
      - ./pocCordApp/build/nodes/PartyA/network-parameters:/opt/corda/network-parameters
      - ./pocCordApp/build/nodes/PartyA/logs:/opt/corda/logs
      - ./pocCordApp/build/nodes/PartyA/drivers:/opt/corda/drivers
      - ./pocCordApp/build/nodes/PartyA/persistence:/opt/corda/persistence
      - ./pocCordApp/build/nodes/PartyA/additional-node-infos:/opt/corda/additional-node-infos
      # the following makes deployNode dir layout compatible with the expectations of the docker image
      - ./pocCordApp/build/nodes/PartyA/persistence.mv.db:/opt/corda/persistence/persistence.mv.db
      - ./pocCordApp/build/nodes/PartyA/persistence.trace.db:/opt/corda/persistence/persistence.trace.db
      - ./pocCordApp/build/nodes/PartyA/node.conf:/etc/corda/node.conf