/* AUTH */
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

/* PROVIDER */
export const UPLOAD = "UPLOAD";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const FETCH_ENCRYPTED_REWARDS_DATA = "FETCH_ENCRYPTED_REWARDS_DATA";
export const FETCH_ENCRYPTED_REWARDS_DATA_SUCCESS = "FETCH_ENCRYPTED_REWARDS_DATA_SUCCESS";
export const FETCH_ENCRYPTED_REWARDS_DATA_ERROR = "FETCH_ENCRYPTED_REWARDS_DATA_ERROR";
export const FETCH_DECRYPTED_REWARDS_DATA = "FETCH_DECRYPTED_REWARDS_DATA";
export const FETCH_DECRYPTED_REWARDS_DATA_SUCCESS = "FETCH_DECRYPTED_REWARDS_DATA_SUCCESS";
export const FETCH_DECRYPTED_REWARDS_DATA_ERROR = "FETCH_DECRYPTED_REWARDS_DATA_ERROR";

/* CONSUMER */
export const AGGREGATION_REQUEST = "AGGREGATION_REQUEST";
export const AGGREGATION_REQUEST_SUCCESS = "AGGREGATION_REQUEST_SUCCESS";
export const AGGREGATION_REQUEST_ERROR = "AGGREGATION_REQUEST_ERROR";
export const FETCH_ENCRYPTED_DATA_OUTPUT = "FETCH_ENCRYPTED_DATA_OUTPUT";
export const FETCH_ENCRYPTED_DATA_OUTPUT_SUCCESS = "FETCH_ENCRYPTED_DATA_OUTPUT_SUCCESS";
export const FETCH_ENCRYPTED_DATA_OUTPUT_ERROR = "FETCH_ENCRYPTED_DATA_OUTPUT_ERROR";
export const FETCH_DECRYPTED_DATA_OUTPUT = "FETCH_DECRYPTED_DATA_OUTPUT";
export const FETCH_DECRYPTED_DATA_OUTPUT_SUCCESS = "FETCH_DECRYPTED_DATA_OUTPUT_SUCCESS";
export const FETCH_DECRYPTED_DATA_OUTPUT_ERROR = "FETCH_DECRYPTED_DATA_OUTPUT_ERROR";